# Generated by Django 6.0.6 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('resume_downloads', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio Stats',
                'verbose_name_plural': 'Portfolio Stats',
            },
        ),
    ]
